#!/usr/bin/env php
<?php

require __DIR__.'/vendor/autoload.php';

use Symfony\Component\Config\FileLocator;
use Symfony\Component\DependencyInjection\ContainerBuilder;
use Symfony\Component\DependencyInjection\Loader\XmlFileLoader;
use Symfony\Component\Console\Application;
use Ginn\Fossil\LicenseCommand;

$container = new ContainerBuilder();
$loader = new XMLFileLoader($container, new FileLocator(__DIR__.'/config'));
$loader->load('services.xml');

$output = $container->get('symfony.console_output');

$application = $container->get('symfony.application');
$application->run(null, $output);
